/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panelimage;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jonatanLara
 */
public class MainForm extends JFrameImage{
    
    /**
     * Creates new form MainForm
     */
     private int contador;
     private int bandera=0;
     
    public MainForm() {
        initComponents();
        Temadefault();
        start();
        
    }
  
       public class conteo extends Thread{
        
        @Override
        public void run(){
            while (bandera==0) {                
                try {
                   
                   
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                    contador++;
                 System.out.println(""+contador);
                    
                    if (contador==10) {
                      //  System.out.println("hola");
                        Tema1();
                    }
                     if (contador==20) {
                        //System.out.println("hola amigo");
                        Tema2();
                    }
                      if (contador==30) {
                        //System.out.println("hola como estas");
                          Tema3();
                    }
                      if (contador==40) {
                          Tema4();
                        
                    }
                      if (contador==50) {
                        Tema5();
                    }
                      if (contador==60) {
                          Temadefault();
                        contador =0;
                        
                    }
                
                
            }
        }
    }  
        
       public void start(){
          conteo c = new conteo();
           bandera=0;
            c.start();
            contador=0;
          
        }  
       public void stop(){
           bandera = 1;
        }
       public void Temadefault(){
           setImage("/image/fondo5.jpg");
        }
       public void Tema1(){
           setImage("/image/fondo1.jpg");
        }
       public void Tema2(){
           setImage("/image/fondo2.jpg");
        }
       public void Tema3(){
           setImage("/image/fondo3.jpg");
        }
       public void Tema4(){
           setImage("/image/fondo4.jpg");
        }
       public void Tema5(){
           setImage("/image/fondo6.jpg");
        }
       
       
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menudefault = new javax.swing.JMenuItem();
        timers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Folders-OS-Windows-8-Metro-icon.png"))); // NOI18N
        jMenuItem2.setText("Tema #1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Windows-Media-Center-icon (1).png"))); // NOI18N
        jMenuItem1.setText("Tema #2");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Windows-Media-Center-icon.png"))); // NOI18N
        jMenuItem3.setText("Tema #3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Windows-icon (1).png"))); // NOI18N
        jMenuItem4.setText("Tema #4");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/windows-icon.png"))); // NOI18N
        jMenuItem5.setText("Tema #5");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        menudefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Network-MAC-icon.png"))); // NOI18N
        menudefault.setText("Default");
        menudefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudefaultActionPerformed(evt);
            }
        });
        jMenu1.add(menudefault);

        timers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Reloj-arena-icon.png"))); // NOI18N
        timers.setText("Timer");
        timers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timersActionPerformed(evt);
            }
        });
        jMenu1.add(timers);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda?");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.out.println("stop");
        stop();
        Tema1();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        stop();
        Tema2();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       stop();
        Tema3();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
      stop();
        Tema4();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        stop();
        Tema5();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menudefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudefaultActionPerformed
        // TODO add your handling code here:
        stop();
        Temadefault();
    }//GEN-LAST:event_menudefaultActionPerformed

    private void timersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timersActionPerformed
        // TODO add your handling code here:
        System.out.println("incia");
        start();
    }//GEN-LAST:event_timersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menudefault;
    private javax.swing.JMenuItem timers;
    // End of variables declaration//GEN-END:variables
}
